### ISSUE TITLE
Wrong uncle rewards

### ISSUE THREAD

**Issue by ahonder** [etclabscore/open-etc-pool#13]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````
Branch is fix payout. Running on pool, found an uncle block and reward is 0.064ETC.Fix not working. Fresh installed.
Look at issue #7  attached screenshot

**Comment by cristianvsl** [comment]
Does the uncle rewards have changed??
27/11/2020, 03:42:12	13%	0.064000	Uncle

0.064 ETC reward for uncle....

**Comment by ahonder** [comment]
maybe not fixed correctly yet

**Comment by cristianvsl** [comment]
I found 2 blocks and one uncle. got paid 6.464. 3.2 + 3.2 + 0.064. Im guessing the uncle reward dropped from 1.25 to 0.064 (in half) ..

**Comment by iquidus** [comment]
try https://github.com/etclabscore/open-etc-pool/commit/28da721b323858faea996de878a8dcd20dc24772
