### ISSUE TITLE
Network hashrate issue

### ISSUE THREAD

**Issue by firxgroup** [etclabscore/open-etc-pool#15]
Hi! I'm playing around with this etc pool after using the open-ethereum-pool original project by Sammy007 for a while. Everything works fine as expected following the step by step installation guide but the only issue is that the displayed Network Hashrate on the web interface is the Network Hashrate of Ethereum and not ETC...

![etc-github](https://user-images.githubusercontent.com/75738008/101999756-82d0e080-3ce0-11eb-9567-8104e60fa994.jpg)

Did any of you ever experienced this issue?

**Comment by cristianvsl** [comment]
That's because you started geth without '--classic' correct way is 'geth --classic and the rest of your command line'
Also when you generate a new address you need to start geth with --classic option ex. 'geth --classic account new'.
Peace

**Comment by firxgroup** [comment]
Ok nice didn't know it was that easy thanks a lot! :)
