### ISSUE TITLE
Stats API Temporarily Down

### ISSUE THREAD

**Issue by goodthebest** [etclabscore/open-etc-pool#16]
Everything setup smoothly, miners can connect to pool but website is not showing stats  and I'm getting Stats API Temporarily Down.

I've made changes correctly in www/config/environment.js and re-built frontend however getting still Stats API Temporarily Down. Please advise?

**Comment by cristianvsl** [comment]
I have a working pool with daily income show and graph. https://etc.mining-pub.com

I will release all the files soon

**Comment by cristianvsl** [comment]
You didn’t follow the guide EXACTLY. Or you didn’t set up Nginx properly

**Comment by cristianvsl** [comment]
Cristian.vsl@outlook.com you can contact me if you want it earlier

**Comment by cristianvsl** [comment]
And as you can see on my pool I did it with https which was a nightmare
