### ISSUE TITLE
Does pool really work?

### ISSUE THREAD

**Issue by alptolga** [etclabscore/open-etc-pool#25]
I just want to know that that does open etc pool really work? I tried many things but I couldn't be succesfull.

**Comment by alptolga** [comment]
I just want to know that that does open etc pool really work? I tried many things but I couldn't  be succesfull.

**Comment by m3b0ss** [comment]
Yes. the pool works but the requirements does not really seem to be true
I have managed to create and use it

**Comment by alptolga** [comment]
If it works, why are the programs and steps required for installation not updated? This situation is a nightmare. I'm going crazy for 2 days.

**Comment by m3b0ss** [comment]
https://gitter.im/miningcore/Lobby?at=5d95c5365173c33ca15dc3c3 go here, read the chat from FEB 02 between m3b0ss ( thats me) and Don Kingdon
I mixed his pool and open-etc-pool to get it working
try to get it from there, u will seee our discussion

**Comment by m3b0ss** [comment]
i have installed the dependencies he had on his pool

**Comment by alptolga** [comment]
a few hours ago we chatted together and also I tried to install your pool too. but I lived some problem. one of them is go 1.6.2 isn't working. but it works with 1.6 the other one is make finished with errors.
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1

Can you help me?
