### ISSUE TITLE
Can add highcart and estimated earnings? 

### ISSUE THREAD

**Issue by ahonder** [etclabscore/open-etc-pool#3]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````
Can you add highcharts and estimated earnings. And a little bit frontend customization too.

**Comment by iquidus** [comment]
Thanks for the PR.

referencing here: https://github.com/etclabscore/open-etc-pool/pull/9
