### ISSUE TITLE
Stale shares

### ISSUE THREAD

**Issue by Racing1** [etclabscore/open-etc-pool#5]
Have had pool running for a week with no problems and finding blocks. Today all of a sudden all shares are stale?? Using latest LolMiner

**Comment by iquidus** [comment]
This is core-geth related. See https://github.com/etclabscore/core-geth/pull/236

Either rebuild core-geth from master branch (the PR is merged), or wait for the next release.

**Comment by iquidus** [comment]
also, clear ~/.etchash there may be corrupt caches on disk
