### ISSUE TITLE
incorrect uncle rewards

### ISSUE THREAD

**Issue by iquidus** [etclabscore/open-etc-pool#7]
Mentioned in discord by joker.

'Hi, I'm using open-etc-pool but I have problem with uncle blocks.
We are getting an incorrect block uncle reward , 2.8 etc is shared to all miners, but the pool received only 0.1 ETC'

**Comment by ahonder** [comment]
ECIP 1017 not implemented on master branch?

**Comment by iquidus** [comment]
it is, for blocks, at least.

https://github.com/etclabscore/open-etc-pool/blob/master/payouts/unlocker.go#L33-L38

**Comment by ahonder** [comment]
If everything is ready, I'll replace my existing pool with this one. waiting thanos hardfork, here is my pool; etcturk.com

**Comment by ahonder** [comment]
![image](https://user-images.githubusercontent.com/42313685/100372760-cd810600-301a-11eb-96b1-5fb81bfe9dc9.png)

after apply uncle reward fix giving that another wrong calculation. Uncle reward is not 0.1 ETC?  showing 0.064ETC
